### ISSUE TITLE
quick step forward bug

### ISSUE THREAD

**Issue by frappuccino220** [justinmeister/Mario-Level-1#17]
hi, when trying to make small steps, ie
when repeadetly pressing the right arrow -> key, mario is supposed to move a pixel to the right,
instead he stays in place or moves one pixel to the left (backwards)..
when doing the same in the other direction (facing left) with the left arrow key <-, the game behaves as expected
other than that, great job, congratulations!

**Comment by justinmeister** [comment]
One year later and this bug is fixed!  Turns out it was a rounding thing.  Just added round() did the trick.  I also set 0.5 as the minimum velocity when the keys are down to prevent a walk animation without movement.
