### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by RonanC** [justinmeister/Mario-Level-1#18]
When I run:
`pip install -r requirements.txt`

I get:
``
Could not find a version that satisfies the requirement pygame==1.9.1release (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for pygame==1.9.1release (from -r requirements.txt (line 1))
``

I am on OSX El Capitan using Conda.
I tried installing via pip and conda.
Also with python 2 and 3 environments.

Do I need to install pygame from the official site on my computer?

**Comment by justinmeister** [comment]
To be honest it usually makes more sense to install pygame and its dependencies separately.  Just use the link on the pygame site for python 2 ( http://pygame.org/download.shtml ) or google how to install pygame for python 3.
